name: Run Python Tests

on:
  pull_request:
    branches: [non-existant-branch]  # Edit this to run tests on what branch you want

jobs:
  test-project:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    
    # Service containers to run with `container-job`
    # NOTE: Use postgres service only if you are using postgres database
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
    env:
      DEBUG: true
      SECRET_KEY: test_secret_key
      ENCRYPTING_KEY: ${{ secrets.ENCRYPTING_KEY }}
      TEST_DB_NAME: test_db
      TEST_DB_USER: test_user
      TEST_DB_PASSWORD: test_password

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        cd src
        mkdir logs
        pytest
